formatter: "markdown"

header-from: ./.config/header.md
footer-from: ./.config/footer.md

output:
  file: ./README.md
  mode: replace
  template: |-
    {{ .Content }}

sections:
  hide:
    - modules

content: |-
  {{ .Header }}

  # Helm release Terraform module
  A Terraform module which configures your Helm release. You can find more information at [this](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) page.

  ## Example
  ```hcl
  {{ include "./example/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}
